microbitmatrix: wip on support for microbit v2
tinygo-org/drivers pull request #222
Opened 2021-01-24 20:38 UTC by deadprogram

This is WIP on support for the microbit v2.

V2 is not yet working, but at least allows both v1 and v2 to be compiled.

2021-01-24 20:38 UTC, deadprogram commented
@conejoninja maybe you can help me take a look into why it is not working for v2?

2021-01-24 20:45 UTC, deadprogram commented
This PR for sure requires https://github.com/tinygo-org/tinygo/pull/1595 but still does not work as expected.

2021-01-24 21:32 UTC, conejoninja commented
I'm unable to find a diagram of the v2, but pin numbers seem ok. What issues are you experiencing? Let's try to enable one led and see if that works. Does the code work on v1?

2021-01-24 21:46 UTC, deadprogram commented
This program can run on the v2: https://github.com/tinygo-org/tinygo/blob/microbit-v2-matrixpins/src/examples/microbit-blink/microbit-blink.go

2021-01-25 08:14 UTC, conejoninja commented
We'll need to perform some tests. I couldn't find the electric diagram, nor some example code, maybe we need to made some changes on the order of the columns/rows in "Display" function.


Please try this:
test 1
```go 
for {
        display.EnableAll()
        time.Sleep(1000*time.Millisecond)
        display.DisableAll()
        time.Sleep(1000*time.Millisecond)
}
```


test 2
```go 
x := int16(1)
y := int16(2)
c := color.RGBA{255, 255, 255, 255}
for {
        display.SetPixel(x,y,c)
        display.Display();
        time.Sleep(1000*time.Millisecond)
        display.DisableAll()
        time.Sleep(1000*time.Millisecond)
}
```
change values of x,y to see if it lit the correct pixel, then try enabling a whole row or column

2021-01-25 22:49 UTC, deadprogram commented
Thanks for the assist @conejoninja now working with my latest commit and https://github.com/tinygo-org/tinygo/pull/1595

2021-01-26 09:23 UTC, deadprogram commented
The build failures are not related to this PR. See https://github.com/tinygo-org/tinygo/issues/1599

2021-01-27 23:02 UTC, deadprogram commented
Refactored to eliminate duplicate code with v1/v2 and rebased against `dev` so tests should now be passing.

2021-01-28 08:16 UTC, deadprogram commented
@conejoninja ready for review again, and is fully working.

2021-01-28 08:23 UTC, conejoninja commented on microbitmatrix/microbitmatrix-v1.go
> +func (d *Device) Size() (w, h int16) {
Could this be in microbitmatrix.go to avoid repetition? Both matrices are 5x5

2021-01-28 08:24 UTC, conejoninja requested changes
func Size() is repeated in v1 and v2, since both are 5x5 we could put it in microbit.go

2021-01-28 09:06 UTC, deadprogram commented
I kept them separate only because there might be other matrix displays we can support with only a few changes.

2021-01-28 09:09 UTC, merged

2021-01-28 09:09 UTC, conejoninja commented
In that case, if it works, let's merge it. Great work, thanks.