i2csoft: add support for software I2C
tinygo-org/drivers pull request #319
Opened 2021-09-22 14:35 UTC by sago35

Added I2C software implementation for esp8266, esp32, etc.
It can also be used for atsamd51 and others, but be aware that it is not a very accurate process.

Since the esp32 has hardware I2C, it should really implement hardware I2C instead of SI2C.
However, I thought I would lose motivation if I implemented the hardware I2C driver first, so I implemented the software I2C first.

https://github.com/tinygo-org/tinygo/pull/2125

2021-09-23 02:32 UTC, sago35 commented
The code has been cleaned up for the first version.
Also, added an argument to New() to make it compatible with other drivers.

2021-09-23 02:34 UTC, sago35 commented on i2csoft/i2csoft_atsamd51.go
> +	// 17 : about 97kHz
The setting values for samd51 (120MHz) and samd21 (48MHz) are now almost identical. Is it possible that samd21 is faster? Or is samd51 slower?

2021-09-23 03:09 UTC, sago35 commented
Now ready for review.

2021-09-23 15:29 UTC, aykevl reviewed
Thank you for this PR! I've been hoping someone would make it for a while :)

One suggestion: perhaps it's easier to only support 100kHz. That should simplify the timing logic and is probably supported by most/all I2C devices.

> Since the esp32 has hardware I2C, it should really implement hardware I2C instead of SI2C.
However, I thought I would lose motivation if I implemented the hardware I2C driver first, so I implemented the software I2C first.

It is still useful, for example if you need more I2C peripherals than the hardware supports.

2021-09-23 15:29 UTC, aykevl commented on i2csoft/i2csoft.go
> +		baudrate: 100 * 1e3,
You can also write this as `100e3`, or even `100_000`. I think that's clearer than `100 * 1e3`.

2021-09-23 15:29 UTC, aykevl commented on i2csoft/i2csoft.go
> +	i2c.SetBaudRate(config.Frequency)
Now you're setting the baudrate again? First here:

```go
	if config.Frequency != 0 {
		i2c.baudrate = config.Frequency
	}
```

And now here, but unconditionally.

2021-09-23 15:29 UTC, aykevl commented on i2csoft/i2csoft.go
> +func (i2c *I2C) WriteByte(data byte) error {
This is an unexported function that cannot return an error, so I think the `error` return can be removed.

2021-09-23 15:29 UTC, aykevl commented on i2csoft/i2csoft_atsamd51.go
> +	// 17 : about 97kHz
What do these values mean?

2021-09-23 15:29 UTC, aykevl commented on i2csoft/i2csoft_atsamd51.go
> +	}
The loop itself will likely be a bigger overhead than the `nop` instruction itself. You can perhaps make it more consistent with some more nops:

```go
for i := 0; i < wait; i++ {
    arm.Asm(`
        nop
        nop
        nop
        nop`)
}
```

2021-09-23 15:29 UTC, aykevl commented on i2csoft/i2csoft_esp32.go
> +		device.Asm(`nop`)
The `nop` instruction is supported in nearly every architecture, so if that helps you can probably use `device.Asm("nop")` in a shared file (this is also supported on ARM).

2021-09-24 00:17 UTC, sago35 commented on i2csoft/i2csoft.go
> +		baudrate: 100 * 1e3,
Changed to 100e3.

2021-09-24 00:19 UTC, sago35 commented on i2csoft/i2csoft.go
> +	i2c.SetBaudRate(config.Frequency)
I'm wrong.
I will correct it.

2021-09-24 00:22 UTC, sago35 commented on i2csoft/i2csoft.go
> +func (i2c *I2C) WriteByte(data byte) error {
Changed WriteByte to a private function.
Removed the return values of writeByte and sendAddress.

2021-09-24 01:18 UTC, sago35 commented on i2csoft/i2csoft_atsamd51.go
> +	// 17 : about 97kHz
That was my note for wait.
I have corrected the comment.

2021-09-24 01:20 UTC, sago35 commented on i2csoft/i2csoft_atsamd51.go
> +	}
I don't think overhead is going to be a problem now.
The reason is that it is easier to adjust if the process is completed in as short a time as possible.

2021-09-24 01:21 UTC, sago35 commented
I have corrected the part you commented on.
Please review again.

2021-09-24 01:32 UTC, sago35 commented
There was a problem with gofmt, which has been fixed.
I'm still using go1.16, but I didn't notice it because it's not an error in go1.16.

2021-10-21 12:49 UTC, sago35 commented
It would be great if you could review it. @aykevl

2021-10-21 13:23 UTC, aykevl requested changes
I think this driver would be much more useful if it didn't contain code for each chip separately.

You can actually write a generic version quite easily. If you want to make the wait time 100kHz, and the chip is 16MHz, that means you need to wait for 160 cycles. So you can calculate the number of cycles quite easily:

```go
cycles := machine.CPUFrequency() / 100e3
```

Then you can wait for the correct amount of cycles. Something like this:

```go
for i := cycles / 8; i != 0; i-- {
    device.Asm("nop")
    device.Asm("nop")
    device.Asm("nop")
    device.Asm("nop")
    device.Asm("nop")
    device.Asm("nop")
}
```

Every common RISC chip will need a decrement and a branch, so will take at least two cycles in loop overhead. I'm also doing the loop "backwards" because that's often more efficient (the compiler might not do this optimization). In the case of a 16MHz chip, 160 cycles are needed. Here, we do 160/8=20 repetitions of this loop, which should be enough time.
Because I2C isn't very strict about timing, I think this will be precise enough.

The big advantage is of course that you don't need to write the same code for every chip separately so it is truly portable (the main goal of this i2csoft driver).

2021-10-21 13:23 UTC, aykevl commented on i2csoft/i2csoft.go
> +	i2c.scl.Configure(machine.PinConfig{Mode: machine.PinOutput})
Note that calling `.High()` may not do what you expect before calling `.Configure()`. The API says that `.Configure()` must be called first: https://tinygo.org/docs/reference/machine/#gpio

2021-10-25 09:47 UTC, sago35 commented
@aykevl 
For several targets, I measured with the following code.
The results are as follows, and we cannot make a good wait time from the CPU clock.

For i2c, the clock accuracy is not important, but since it is blocking, it may want to send the data as fast as possible.
I think m4's Frequency is very slow, which is a problem.

| target | clock | I2C Frequency |
| ------ | ----- | --------------- |
| feather-rp2040 | 125MHz | 18kHz |
| feather-m4-can | 120MHz | 9kHz |
| feather-stm32f405 | 168MHz | 19kHz |
| qtpy (m0) | 48Mhz | 17kHz |
| feather-nrf52840-sense | 64MHz | 19kHz |

```go
package i2csoft

import (
	"device"
	"machine"
)

// wait waits for half the time of the SCL operation interval.
func (i2c *I2C) wait() {
	cycles := machine.CPUFrequency() / 100e3

	for i := cycles / 8; i != 0; i-- {
		device.Asm("nop")
		device.Asm("nop")
		device.Asm("nop")
		device.Asm("nop")
		device.Asm("nop")
		device.Asm("nop")
	}
}
```

2021-10-25 09:48 UTC, sago35 commented on i2csoft/i2csoft.go
> +	i2c.scl.Configure(machine.PinConfig{Mode: machine.PinOutput})
I've updated the code.

2021-10-25 09:57 UTC, sago35 commented
I tried changing the number of nop.
Is the overhead of device.Asm() too large?

* feather-rp2040
    * nop x 24 : 7kHz
    * nop x 12 : 12kHz
    * nop x 6 : 18kHz
    * nop x 1 : 34kHz

```go
package i2csoft

import (
	"device"
	"machine"
)

// wait waits for half the time of the SCL operation interval.
func (i2c *I2C) wait() {
	cycles := machine.CPUFrequency() / 100e3

	for i := cycles / 8; i != 0; i-- {
		device.Asm("nop")
	}
}
```

2021-11-03 18:11 UTC, deadprogram commented
Are there any other changes pending on this PR? @sago35 @aykevl it seems like most, but not all, of the questions have been addressed or answered. What more is needed here?

2021-11-04 13:18 UTC, sago35 commented
@deadprogram @aykevl 
The change request from aykevl is to remove the handling of each chip.
However, at this point, I think it is better to keep the per-chip handling.
In particular, the performance of atsamd51 is very slow.
The slower the Frequency, the longer i2csoft's processing will be blocked.

Removing per-chip handling should be considered in another PR.

2021-11-04 14:02 UTC, deadprogram commented
> Removing per-chip handling should be considered in another PR.

Works for me!

Thanks for all your efforts on this PR @sago35 and thanks for reviewing @aykevl 

Now merging.

2021-11-04 14:02 UTC, merged