Add GC9A01 Driver
tinygo-org/drivers pull request #452
Opened 2022-08-27 14:19 UTC by lmatte7

This PR adds driver support for the Waveshare 1.28in circular [display](https://www.waveshare.com/1.28inch-lcd-module.htm). A lot of the code was based on the driver code for ST7735 with specific updates for this board. The full datasheet is available [here](https://www.waveshare.com/w/upload/5/5e/GC9A01A.pdf).

The driver has been tested and can successfully run the display with a RPI Pico and a ESP32.

2022-09-06 11:31 UTC, deadprogram commented
Any comments @sago35 or @conejoninja before merging?

2022-09-06 12:00 UTC, sago35 requested changes
@lmatte7 
For the most part, I think it is very good.
I commented because I would like to make the same design as other drivers.

Please update README.md.
Add a test to smoke-test in the Makefile.

If possible, please keep the interface in the same form as the st7735 and ili9341 interfaces.
In other words, we want int16 to be used instead of int32 in many places.
https://github.com/tinygo-org/drivers/blob/release/st7735/st7735.go
https://github.com/tinygo-org/drivers/blob/v0.22.0/ili9341/ili9341.go

2022-09-06 12:00 UTC, sago35 commented on gc9a01/gc9a01.go
> +func (d *Device) SetPixel(x, y int32, c color.RGBA) {
Make it to satisfy drivers.Displayer.

https://github.com/tinygo-org/drivers/blob/v0.22.0/displayer.go#L5-L14

2022-09-06 12:00 UTC, sago35 commented on gc9a01/gc9a01.go
> +}
Make it to satisfy drivers.Displayer.

https://github.com/tinygo-org/drivers/blob/v0.22.0/displayer.go#L5-L14

2022-09-06 12:00 UTC, sago35 commented on gc9a01/gc9a01.go
> +func (d *Device) Size() (w, h int32) {
Make it to satisfy drivers.Displayer.

https://github.com/tinygo-org/drivers/blob/v0.22.0/displayer.go#L5-L14

2022-09-06 13:54 UTC, lmatte7 commented
@sago35 Thanks for the feedback! I’ll make the changes and send an update.

2022-09-13 23:07 UTC, sago35 commented
I will review it tomorrow or so.

2022-09-17 05:00 UTC, sago35 requested changes
@lmatte7 
Please add sleep to examples.
I will approve if you add it.

2022-09-17 05:00 UTC, sago35 commented on examples/gc9a01/main.go
> +
Please add sleep, etc. so that the main function does not terminate.
https://github.com/tinygo-org/drivers/blob/release/examples/ili9341/basic/main.go#L33-L35

2022-09-18 04:11 UTC, sago35 approved these changes
LGTM
Thank you!

2022-09-18 13:21 UTC, deadprogram commented
Now going to squash/merge thank you for working on this @lmatte7

2022-09-18 13:22 UTC, merged